% %round(-99.97855)
% %round(99.97855)
% %ceil(99.87855)
% %ceil(-99.87855)
% %floor(99.87855)
% %floor(-99.87855)
% %fix(50.55555)
% %fix(-50.55555)
% t=-pi:0.1:pi
% X=sin(t)
% subplot(2,3,1)
% plot(t,X)
% xlabel('t')
% ylabel('sin(t)')
% title('Sin(t)')
% % subplot(1,2,2)
% % stem(t,X)
% % xlabel('t')
% % ylabel('sin(t)')
% % title('Sin(t)')
% Y=cos(t)
% subplot(2,3,2)
% plot(t,Y)
% xlabel('t')
% ylabel('cos(t)')
% title('Cos(t)')
% % subplot(1,2,2)
% % stem(t,Y)
% % xlabel('t')
% % ylabel('cos(t)')
% % title('Cos(t)')
% t=(-pi/2)+0.05:0.05:(pi/2)-0.05
% Z=tan(t)
% subplot(2,3,3)
% plot(t,Z)
% xlabel('t')
% ylabel('tan(t)')
% title('Tan(t)')
% % subplot(1,2,2)
% % stem(t,Z)
% % xlabel('t')
% % ylabel('tan(t)')
% % title('Tan(t)')
% t=-1:0.02:1
% X=asin(t)
% subplot(2,3,4)
% plot(t,X)
% xlabel('t')
% ylabel('asin(t)')
% title('Cosec(t)')
% % subplot(1,2,2)
% % stem(t,X)
% % xlabel('t')
% % ylabel('asin(t)')
% % title('Cosec(t)')
% X=acos(t)
% subplot(2,3,5)
% plot(t,X)
% xlabel('t')
% ylabel('acos(t)')
% title('Sec(t)')
% % subplot(1,2,2)
% % stem(t,X)
% % xlabel('t')
% % ylabel('acos(t)')
% % title('Sec(t)')
% t=-5:0.1:5
% X=atan(t)
% subplot(2,3,6)
% plot(t,X)
% xlabel('t')
% ylabel('atan(t)')
% title('Cot(t)')
% % subplot(1,2,2)
% % stem(t,X)
% % xlabel('t')
% % ylabel('atan(t)')
% % title('Cot(t)')
% %X=1:1:20
% % Y=log(X)
% % plot(X,Y)
% % title('Log(X)')
% % xlabel('Values of X')
% % ylabel('log x')
% % Y=log10(X)
% % plot(X,Y)
% % title('Log10 (X)')
% % xlabel('Values of X')
% % ylabel('log 10 x')
% % Y=sqrt(X)
% % plot(X,Y)
% % title('Sqrt (X)')
% % xlabel('Values of X')
% % ylabel('sqrt (x)')
% % Y=nthroot(X,5)
% % plot(X,Y)
% % title('5th Root (X)')
% % xlabel('Values of X')
% % ylabel('5th root (x)')